name: Backend Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      FRONTEND_URL: ${{ env.FRONTEND_URL }}
      PORT: ${{ env.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: backend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
